# Configuração de Build para a Netlify
[build]
  # Diz à Netlify que a pasta principal do seu site é esta mesma
  publish = "." 
  # Diz à Netlify onde encontrar a sua "cozinha" segura com os robôs
  functions = "netlify/functions"
